### PR TITLE
Configure mail confirmation within the backend order form

### PR DESCRIPTION
**Pull request by Kevinschmid86**
At the moment it is not possible to configure the behavior of the confirmation mails. Currently every new backend order will also send a confirmation mail.
This change applies one new checkbox at the bottom to decide whether send a confirmation mail or not.

shopware_image_two

A new global configuration is available to decide which default value should be used.

shopware_image_one

During the acitivation of the plugin the global Shopware Configuration sendOrderMail is considered and set as a default value within the plugin. 
If the global value sendOrderMail changes in the future from true to false, the plugin backend plugin configuration will be always set to false.

### CODE REVIEW

**Comment by Kevinschmid86** [comment]
Hey @mitelg 
as discussed before here is the new PR with clean changes. 
Since your last master branch still one problem exists with the first initialization of the backend order window. 
If you open it for the first time, the Object getTotalCostsOverview does not exist. 

error_plugin

If I open it another time the object is there. Unfortunately I have no idea which changes of the master branch are responsible for this behavior, maybe you have an idea?

**Comment by klarstil** [comment]
Hey @Kevinschmid86 

the error messages quotes a different error then the one you mentioned. The message is telling you that the object (`me` in this case) is undefined. `me` in this context should be the controller. This usually indicates that the scope is different than expected. Due to the fact we're dealing with a event handler `this` is probably the button the user clicked for example instead of the instance of the controller.

**Comment by Kevinschmid86** [comment]
Hey @klarstil 
thanks for your hint. At the moment I´m still struggling how to solve the checked flag correctly. 
Another thing I tried was to change the file total_costs_overview.js 

`    createSendMailCheckbox: function () {
        var me = this;

        me.sendMailCheckbox = Ext.create('Ext.form.field.Checkbox', {
            boxLabel: '{s name="send_mail"}{/s}',
            inputValue: true,
            uncheckedValue: false,
            padding: '0 5 0 0'
        });

        if(me.orderModel.get('sendMail') == 1) {
            me.sendMailCheckbox.setValue(true);
        }

        return me.sendMailCheckbox;
    },`

When I open the backend order window for the frist time the flag from the orderModel is true. At any other time I open the window the flag is set to false. 

So I´ll try to figure out how to set the value in the main controller. 
Hope I can come back soon with a commit :)

**Comment by Kevinschmid86** [comment]
Hey @mitelg, @klarstil 
I made another commit. Hope this could be ok for you... 
Have a nice Friday.

**Comment by Tmkrth** [comment]
Thanks for the effort Mr Schmid!

How nice it would be if this would get into the main plugin, it would save so much time and effort updating the shop.

**Comment by Kevinschmid86** [comment]
Hey together @mitelg @klarstil , 
has anyone an update for me? Did you have time to think about this PR? Is there any timespan for that? :) 
Many thanks in advance for your answer.

**Comment by mitelg** [comment]
hey @Kevinschmid86 
at the moment this PR is scheduled, but has no specific time line. you can track the status here: https://issues.shopware.com/issues/PT-8194

**Comment by Hotte512** [comment]
please go on with that... ;)

**Comment by Hotte512** [comment]
can i set a bounty on this?

As we need to create orders by hand for our customers we are not that satisfied with shopware backend order atm... The workaround not to send an eMail would be a step to help us in our daily process.

**Comment by mitelg** [comment]
@Kevinschmid86 we finally merged your PR
thanks for your contribution! :+1: :tada:

**Comment by Hotte512** [comment]
WONDERFUL - THX
As we get some orders by phone and fax we are waiting for that! :-)

**Pull request closed without merging**
