### PR TITLE
Consider customer group prices during the product selection

### PR DESCRIPTION
**Pull request by Kevinschmid86**
At the moment the backend plugin doesn´t consider the prices of a customer group if a customer is selected. For merchants who have a lot of merchant customer it is hard to edit the selected prices manually to the correct value. 
With this PR a new param "customerId" was added to the function onArticleSelect, so that the customer group is now available in the query within the productrepository.

### CODE REVIEW

**Comment by mitelg** [comment]
Hello @Kevinschmid86 
thanks for your PR :+1:  please fix your code style regarding our conventions: https://github.com/shopware/shopware/blob/5.2/CONTRIBUTING.md#coding-standards

**Comment by Kevinschmid86** [comment]
Hey @mitelg 
it was my first PR, so that I´m not familiar with the details of your needed code style. With the last commit I tried to fix the issues.

**Comment by mitelg** [comment]
Hi @Kevinschmid86,
no problem. you can use a githook which is provided with this plugin to check your code style. to install it, just execute this command in the plugin directory:
`./.githooks/install_hooks.sh`

**Comment by Kevinschmid86** [comment]
Hey @mitelg 
I played around with some code sniffers in phpstorm. After inspection of code it should be ok now. 
Thanks for your patience.

**Comment by mitelg** [comment]
hey @Kevinschmid86 
we worked on your PR and adjusted it a bit. The changes will be merged soon.
thanks again for your contribution! :+1:

**Pull request closed without merging**
