### PR TITLE
tax fix for view

### PR DESCRIPTION
**Pull request by JonidBendo**

### CODE REVIEW

**Comment by mitelg** [comment]
Hi @JonidBendo 
thanks for your PR.
your changes result in a JS error on this line: https://github.com/shopwareLabs/SwagBackendOrder/blob/master/Resources/views/backend/swag_backend_order/controller/main.js#L394

what is your issue or intention behind your change?

**Comment by JonidBendo** [comment]
Hi @mitelg, the issue was that when you had multiple taxes and the id of one of them matched with the value from another one, for example tax name 7% id 4, tax 19% id 7. If you tried to apply tax 7% you would end up with 19%. There is a weird mismatch like that.

**Comment by mitelg** [comment]
Hey @JonidBendo 
ok, that sounds like a bug :-) 
could you please fix the JS error, so we could merge it?

**Comment by mitelg** [comment]
Hey @JonidBendo 
I am not able to reproduce your issue. my taxes:

id | tax | description
-- | ---- | ---------------
1 | 19.00 | 19%
4 | 7.00 | 7 %
7 | 19.00 | 19%2

I set the third tax to a product and added it to a new order within the module. The column tax shows the right value, 19 and not 7 as you said. Can you confirm this behaviour?

**Comment by mitelg** [comment]
thanks for your contribution @JonidBendo 
Your fix will be merged soon

**Pull request closed without merging**
