### PR TITLE
fixed mistakenly email validation

### PR DESCRIPTION
**Pull request by barbieswimcrew**
Needed to wrap the afterrender event into a timeout due to the fact that field.getValue() may be empty and therefor the email validation takes place even if the automatically inserted guest email is equal to the configured guest email

### CODE REVIEW

**Comment by mitelg** [comment]
@shopwareBot

**Comment by barbieswimcrew** [comment]
Thanks for your reply, I already tried so but unfortunately I got unexpected ExtJS errors then

**Comment by barbieswimcrew** [comment]
Okay, for some reasons now no error occurs anymore... maybe a cache thing. I moved the field value access into the inner timeout function as suggested

**Comment by mitelg** [comment]
we removed the condition, as the validation was never triggered. 
if the issue still exists, please open a ticket on https://issues.shopware.com/ with a detailed description and what the problem is about.

**Pull request closed without merging**
